name: /dev/lawyer
description: law, technology, and the space between
url: https://writing.kemitchell.com
permalink: :year/:month/:day/:title
author: Kyle E. Mitchell
homepage: https://kemitchell.com
highlighter: rouge
excerpt_separator: "<!--jump-->"
repository: kemitchell/writing.kemitchell.com
repository_url: "https://github.com/kemitchell/writing.kemitchell.com"
subscribe_url: "https://groups.io/g/kemitchell"
plugins:
- jekyll-sass-converter
- jekyll-feed
- jekyll-tidy
feed:
  path: atom.xml
exclude:
- vendor
- Gemfile
- Gemfile.lock
- Makefile
- listtags
- serve
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
  - scope:
      path: ""
      type: lists
    values:
      layout: post
  - scope:
      path: ""
      type: living_documents
    values:
      layout: post
collections:
  lists:
    output: true
    permalink: /lists/:title:output_ext
  living_documents:
    output: true
    permalink: /living/:title:output_ext
